name: hello_project
on:
  push:
    branches:
      - dev
jobs:
  name: test_job
  runs-on: ubuntu-latest

  steps:
    - name: Print_hello
    run: |
      echo "Hello World"
      cat README.md
    
