name: hello_project
on:
  push:
    branches:
      - main
jobs:
  test_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print_hello
        run: |
          echo "Hello World"
          echo "Please Momen"
      - name: checkout
        uses: actions/checkout@v4.2.2
    
